export const ui = {
  appName: 'Vesper Desk',
  loginToTwitch: 'Login to Twitch',
  settings: 'Settings',
  layoutTemplates: 'Layout templates',
  changeLayout: 'Change layout',
  standard: 'Standard',
  focus: 'Focus',
  performance: 'Performance',
  sync: 'Sync',
  synced: 'Synced',
  editDesk: 'Edit Desk',
  editDeskUnavailableInFocus: 'Edit Desk is not available in Focus',
  spacing: 'Spacing',
  drag: 'Drag',
  snap: 'Snap',
  done: 'Done',
  dockAllPopouts: 'Dock all pop-outs',
  seeThroughWindows: 'See through windows',
  fullscreen: 'Fullscreen',
  openChat: 'Open chat',
  openChannelChat: (channel: string) => `Open #${channel} chat`,
  ghostOverlay: 'Ghost overlay',
  pinToolbar: 'Pin toolbar',
  popOutChat: 'Pop out chat',
  popOutStream: 'Pop out stream',
  dockBack: 'Dock back',
  hideChat: 'Hide chat',
  closeChat: 'Close chat',
  switchFocus: 'Switch Focus',
  focusMode: 'Focus mode',
  more: 'More',
  menu: 'Menu',
  save: 'Save',
  reset: 'Reset',
  custom: 'Custom…',
  minimize: 'Minimize',
  maximize: 'Maximize',
  restore: 'Restore',
  close: 'Close',
  addStream: 'Add stream',
  searchAdd: 'Add channel…',
  redock: 'Redock',
  alwaysOnTop: 'Always on top',
  lockWindow: 'Lock window',
  toggleToolbar: 'Toggle toolbar',
  quitApplication: 'Quit application',
  appearance: 'Appearance',
  chat: 'Chat',
  hotkeys: 'Hotkeys',
  updates: 'Updates',
  accounts: 'Accounts',
  advanced: 'Advanced',
  help: 'Help',
  logout: 'Log out',
  loggedInAs: (name: string) => `Logged in as ${name}`,
  dark: 'Dark',
  dim: 'Dim',
  light: 'Light',
  accent: 'Accent',
  surface: 'Surface',
  text: 'Text',
  backgroundColor: 'Background color',
  backgroundImage: 'Background image',
  opacity: 'Opacity',
  chrome: 'Chrome',
  chromeTop: 'Top',
  chromeLeft: 'Left',
  chromeRight: 'Right',
  chromeBottom: 'Bottom',
  font: 'Font',
  size: 'Size',
  drawerWidth: 'Drawer width',
  reconnectChat: 'Reconnect chat',
  refreshPrimeSession: 'Refresh Prime session',
  developerClientId: 'Developer Client ID',
  showTips: 'Show tips',
  checkUpdates: 'Check for updates',
  openLogFolder: 'Open log folder',
  saveLayout: 'Save layout',
  deleteLayout: 'Delete',
  layoutName: 'Layout name',
  mute: 'Mute',
  unmute: 'Unmute',
  volume: 'Volume',
  saved: 'Saved',
  removeSaved: 'Remove from Saved',
  renameSaved: 'Rename',
  clearSavedName: 'Clear name',
  playerStopped: 'This player stopped.',
  reloadPlayer: 'Reload player',
  low: 'Low',
  emotes: 'Emotes',
  send: 'Send',
  slideLeft: 'Slide L',
  slideRight: 'Slide R',
  dockBottom: 'Dock bottom',
  float: 'Float',
  sendMessage: 'Send a message',
  chatPaused: 'Chat paused due to scroll',
  moreMessages: 'More messages below',
  messageDeleted: '<message deleted>',
  firstTimeChat: 'First-time chat',
  replyingTo: (name: string) => `Replying to @${name}:`,
  searchEmotes: 'Search emotes',
  yourEmotes: 'Your emotes',
  channelEmotes: 'Channel emotes',
  globalEmotes: 'Global emotes',
  noEmotes: 'No emotes found',
  emoteLocked: 'Subscribe or follow to use',
  slowMode: (seconds: number) => `Slow mode (${seconds}s)`,
  subsOnly: 'Subscriber-only',
  emoteOnly: 'Emote-only',
  followersOnly: 'Followers-only',
  uniqueChat: 'Unique chat',
} as const

export const firstRunTips = [
  {
    id: 'focus',
    title: 'Focus',
    body: 'Focus mode keeps one hero stream large (~72%) with a thin strip for the rest. Click a strip tile or Switch Focus to promote it.',
  },
  {
    id: 'chat',
    title: 'Open chat vs Pop out chat',
    body: 'Open chat pushes an in-app drawer. Pop out chat opens a separate window you can park on another monitor.',
  },
  {
    id: 'see-through',
    title: 'See through windows',
    body: 'Empty stage shows your desktop and unlocks click-through. Lock window freezes click-through while staying see-through.',
  },
  {
    id: 'dock',
    title: 'Dock back',
    body: 'Popped streams leave the grid. Dock back from the pop-out, the redock menu, or Dock all pop-outs. Window X docks.',
  },
] as const
